version: '3'

services:
    neo4j:
        image: "neo4j:latest"
        ports:
            - "127.0.0.1:7474:7474"
            - "127.0.0.1:7687:7687"
        volumes:
            - neo4j-data:/data
        network_mode: "bridge"

volumes:
    neo4j-data:
        driver: local
